baseurl = "https://yurikitoksp.github.io/blog/"
languageCode = "en-us"
title = "Yuriko Sosa"
theme = "hyde-mod"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
rssLimit = 3

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
[[menu.main]]
    name = "Tags"
    url = "/tags/"
[[menu.main]]
    name = "Categories"
    url = "/categories/"

[params]
    description = "A blog where I write about RStats and Psychometrics."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    themeColor = "theme-base-harvard"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
